pull and compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,10 +1,75 @@
 #!/usr/bin/env bash
 
-echo "-----> Installing avconv"
-# change to the the BUILD_DIR ($1)
-cd $1
-# download the binary (-O) silently (-s)
-curl https://s3-us-west-2.amazonaws.com/marmoset-libav/libav-release-64bit-static.tar.xz -s -O -L
-# untar the binary to the directory we want
-tar -C vendor -xvf libav-release-64bit-static.tar.xz
-mv ./vendor/libav-12-64bit-static/avconv ./bin/avconv
+indent() {
+    sed -u 's/^/       /'
+}
+
+echo '-----> Install Libav'
+
+BUILD_DIR=$1
+CACHE_DIR=$2
+VENDOR_DIR="${BUILD_DIR}/vendor"
+INSTALL_DIR="${VENDOR_DIR}/libav"
+CACHE_FILE="${CACHE_DIR}/libav.tar.gz"
+LIBAV_VERSION="${LIBAV_VERSION:-12.3}"
+LIBAV_VERSION_MAJOR=$(printf "%s" "$LIBAV_VERSION" | sed 's/\..*$//')
+
+CONFIG_DIR="/etc/libav-$LIBAV_VERSION_MAJOR"
+
+if [ ! -f "$CACHE_FILE" ]; then
+    # install libav
+    LIBAV_FILE="libav-${LIBAV_VERSION}.tar.xz"
+    LIBAV_DIR="libav-$LIBAV_VERSION"
+    LIBAV_URL="https://libav.org/releases/${LIBAV_FILE}"
+
+    echo "-----> Downloading libav $LIBAV_VERSION_MAJOR from $LIBAV_URL"
+    wget "$LIBAV_URL" -P "$BUILD_DIR" | indent
+
+    echo "-----> Extracting libav package"
+    if [ ! -f "${BUILD_DIR}/${LIBAV_FILE}" ]; then
+        echo "Error: package download failed? (expected ${BUILD_DIR}/${LIBAV_FILE})" | indent
+        ls $BUILD_DIR | indent
+        exit 1
+    fi
+    tar xvf "${BUILD_DIR}/${LIBAV_FILE}" | indent
+
+    echo "-----> Building libav"
+    cd "$LIBAV_DIR"
+    export CFLAGS="-I${INSTALL_DIR}/include"
+    export LDFLAGS="-L${INSTALL_DIR}/lib"
+    ./configure --prefix="$INSTALL_DIR"
+    make && make install
+    cd ..
+    rm -rf "$LIBAV_DIR"
+
+    echo "-----> Caching built stuff"
+    cd "$VENDOR_DIR"
+    REL_INSTALL_DIR="libav"
+    tar czf "${REL_INSTALL_DIR}.tar" "${REL_INSTALL_DIR}"
+
+    if [ ! -d "$CACHE_DIR" ]; then
+        mkdir -p "$CACHE_DIR"
+    fi
+
+    mv "${REL_INSTALL_DIR}.tar.gz" "$CACHE_FILE"
+
+else
+
+    echo "-----> Extracting cached libav $CACHE_FILE -> $VENDOR_DIR"
+    mkdir -p "$VENDOR_DIR"
+    tar xzf "$CACHE_DIR" -C "$VENDOR_DIR"
+
+fi
+
+cat "${CONFIG_DIR}/policy.xml" > "${INSTALL_DIR}/${CONFIG_DIR}/policy.xml"
+
+echo "-----> Updating environment variables"
+PROFILE_PATH="${BUILD_PATH}/.profile.d/libav.sh"
+ACTUAL_INSTALL_PATH="${HOME}/vendor/libav"
+mkdir -p "$(dirname "$PROFILE_PATH")"
+cat > "$PROFILE_PATH" <<EOF
+export PATH=$ACTUAL_INSTALL_PATH/bin:\$PATH
+export LD_LIBRARY_PATH=$ACTUAL_INSTALL_PATH/lib:\$LD_LIBRARY_PATH:/usr/local/lib
+EOF
+
+echo "-----> All done\~"
